# Generated by Django 2.2.1 on 2019-09-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0005_auto_20190905_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waganeko.Publisher', verbose_name='出版社'),
        ),
    ]
