# Generated by Django 2.2.1 on 2019-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0006_auto_20190905_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='本のカテゴリ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_nums',
            field=models.IntegerField(null=True, verbose_name='ページ数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(max_length=5, null=True, verbose_name='出版年'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(default=0, null=True, verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='カテゴリ'),
        ),
    ]
