# Generated by Django 2.2.1 on 2019-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0009_auto_20190905_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_hiragana',
            field=models.CharField(max_length=30, null=True, verbose_name='著者名ひらがな'),
        ),
    ]
