# Generated by Django 2.2.1 on 2019-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0011_auto_20190905_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_year',
            field=models.CharField(max_length=20, null=True, verbose_name='生まれた年'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pass_away_year',
            field=models.CharField(max_length=20, null=True, verbose_name='享年'),
        ),
    ]
