# Generated by Django 2.2.1 on 2019-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0012_auto_20190905_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='detail',
            field=models.TextField(null=True, verbose_name='著者について詳細'),
        ),
    ]
