# Generated by Django 2.2.1 on 2019-09-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0014_auto_20190905_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='閲覧数'),
        ),
    ]
