# Generated by Django 2.2.1 on 2019-09-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0015_book_view_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='iine_nums',
            field=models.PositiveIntegerField(null=True, verbose_name='いいね数'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='post_for_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waganeko.Book', verbose_name='投稿先の本'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='post_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
