# Generated by Django 2.2.1 on 2019-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0016_auto_20190908_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='post_text',
            field=models.CharField(max_length=225, verbose_name='投稿内容'),
        ),
    ]
