# Generated by Django 2.2.1 on 2019-09-05 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('prefer_book_category', models.IntegerField(choices=[(0, '小説'), (1, '科学')], verbose_name='好きな本のカテゴリ')),
                ('icon_img', models.ImageField(upload_to='image/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
    ]
