# Generated by Django 2.2.4 on 2019-09-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='著者苗字')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='著者名')),
                ('last_name_hiragana', models.CharField(max_length=30, null=True, verbose_name='著者苗字ひらがな')),
                ('first_name_hiragana', models.CharField(max_length=30, null=True, verbose_name='著者名ひらがな')),
                ('born_year', models.CharField(max_length=20, null=True, verbose_name='生まれた年')),
                ('pass_away_year', models.CharField(max_length=20, null=True, verbose_name='享年')),
                ('detail', models.TextField(null=True, verbose_name='著者について詳細')),
                ('author_img', models.ImageField(null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': '著者データ',
                'verbose_name_plural': '著者データ',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50, verbose_name='本の名前')),
                ('book_name_hiragana', models.CharField(max_length=50, null=True, verbose_name='本の名前（読み仮名）')),
                ('first_published_year', models.CharField(max_length=5, null=True, verbose_name='出版年')),
                ('text', models.TextField(null=True, verbose_name='本文')),
                ('category', models.IntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='本のカテゴリ')),
                ('rate', models.IntegerField(default=0, null=True, verbose_name='評価')),
                ('page_nums', models.IntegerField(null=True, verbose_name='ページ数')),
                ('book_img', models.ImageField(null=True, upload_to='image/')),
                ('view_nums', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
            ],
            options={
                'verbose_name': '本データ',
                'verbose_name_plural': '本データ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('prefer_book_category', models.IntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='好きな本のカテゴリ')),
                ('icon_img', models.ImageField(null=True, upload_to='image/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='出版社名')),
                ('other', models.TextField(null=True, verbose_name='詳細')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('post_text', models.TextField(max_length=100, verbose_name='投稿')),
                ('iine_nums', models.PositiveIntegerField(verbose_name='いいね数')),
                ('category', models.PositiveIntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='カテゴリ')),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('post_for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Book', verbose_name='投稿先の本')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'あらすじ',
                'verbose_name_plural': 'あらすじ',
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='評価')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='ユーザー情報')),
            ],
            options={
                'verbose_name': '本評価データ',
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('post_text', models.CharField(max_length=150, verbose_name='投稿内容')),
                ('iine_nums', models.PositiveIntegerField(null=True, verbose_name='いいね数')),
                ('category', models.PositiveIntegerField(choices=[(0, '小説'), (1, '科学')], null=True, verbose_name='カテゴリ')),
                ('posted_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_for_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waganeko.Book', verbose_name='投稿先の本')),
                ('post_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '解説',
                'verbose_name_plural': '解説',
            },
        ),
    ]
