# Generated by Django 2.2.4 on 2019-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='tweet',
            field=models.CharField(default='', max_length=100, verbose_name='ツイート'),
        ),
    ]
