# Generated by Django 2.2.1 on 2019-09-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0002_auto_20190905_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='著者名')),
                ('born_year', models.IntegerField(verbose_name='生まれた年')),
                ('pass_away_year', models.IntegerField(verbose_name='享年')),
                ('detail', models.TextField(verbose_name='著者について詳細')),
                ('author_img', models.ImageField(upload_to='image/')),
            ],
            options={
                'verbose_name': '著者データ',
                'verbose_name_plural': '著者データ',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50, verbose_name='本の名前')),
                ('published_year', models.CharField(max_length=5, verbose_name='出版年')),
                ('text', models.TextField(verbose_name='本文')),
                ('category', models.IntegerField(choices=[(0, '小説'), (1, '科学')], verbose_name='本のカテゴリ')),
                ('rate', models.IntegerField(default=0, verbose_name='評価')),
                ('page_nums', models.IntegerField(verbose_name='ページ数')),
                ('book_img', models.ImageField(upload_to='image/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Author', verbose_name='著者')),
            ],
            options={
                'verbose_name': '本データ',
                'verbose_name_plural': '本データ',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('other', models.TextField(null=True, verbose_name='詳細')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('post_text', models.TextField(max_length=100, verbose_name='投稿')),
                ('iine_nums', models.PositiveIntegerField(verbose_name='いいね数')),
                ('category', models.PositiveIntegerField(choices=[(0, '小説'), (1, '科学')], verbose_name='カテゴリ')),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('post_for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Book', verbose_name='投稿先の本')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'あらすじ',
                'verbose_name_plural': 'あらすじ',
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='評価')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='ユーザー情報')),
            ],
            options={
                'verbose_name': '本評価データ',
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('post_text', models.TextField(verbose_name='投稿内容')),
                ('iine_nums', models.PositiveIntegerField(verbose_name='いいね数')),
                ('category', models.PositiveIntegerField(choices=[(0, '小説'), (1, '科学')], verbose_name='カテゴリ')),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('post_for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Book', verbose_name='投稿先の本')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Profile', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'あらすじ',
                'verbose_name_plural': 'あらすじ',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Publisher', verbose_name='出版社'),
        ),
    ]
