# Generated by Django 2.2.4 on 2019-09-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0003_remove_explanation_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waganeko.Author', verbose_name='著者'),
        ),
    ]
