# Generated by Django 2.2.1 on 2019-09-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0003_auto_20190905_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explanation',
            options={'verbose_name': '解説', 'verbose_name_plural': '解説'},
        ),
    ]
