# Generated by Django 2.2.4 on 2019-09-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0004_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
