# Generated by Django 2.2.1 on 2019-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0004_auto_20190905_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_year',
            field=models.IntegerField(null=True, verbose_name='生まれた年'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='著者名'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pass_away_year',
            field=models.IntegerField(null=True, verbose_name='享年'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon_img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='出版社名'),
        ),
    ]
