# Generated by Django 2.2.4 on 2019-09-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0006_auto_20190910_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='belong',
            field=models.CharField(max_length=30, null=True, verbose_name='所属'),
        ),
    ]
