# Generated by Django 2.2.1 on 2019-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0007_auto_20190905_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name_hiragana',
            field=models.CharField(max_length=50, null=True, verbose_name='本の名前（読み仮名）'),
        ),
    ]
