# Generated by Django 2.2.4 on 2019-09-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0008_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='iine_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='いいね数'),
        ),
    ]
