# Generated by Django 2.2.1 on 2019-09-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0008_book_book_name_hiragana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='first_published_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
