# Generated by Django 2.2.4 on 2019-09-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0009_auto_20190911_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'なるほど～', 'verbose_name_plural': 'なるほど～'},
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waganeko.Explanation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_user', to='waganeko.Profile')),
            ],
            options={
                'verbose_name': '異議あり',
                'verbose_name_plural': '異議あり',
            },
        ),
    ]
