# Generated by Django 2.2.4 on 2019-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0010_auto_20190911_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='igiari_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='異議あり数'),
        ),
    ]
