# Generated by Django 2.2.1 on 2019-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0010_author_name_hiragana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name_hiragana',
            new_name='first_name_hiragana',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='著者苗字'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_hiragana',
            field=models.CharField(max_length=30, null=True, verbose_name='著者苗字ひらがな'),
        ),
    ]
