# Generated by Django 2.2.4 on 2019-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0011_explanation_igiari_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='total_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='合計数'),
        ),
    ]
