# Generated by Django 2.2.4 on 2019-09-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waganeko', '0013_auto_20190911_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='post_for_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='waganeko.Book', verbose_name='投稿先の本'),
        ),
    ]
